config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "/" => "home#index"
  resources :users
  resources :customers
  resources :owners
  resources :menu
  resources :carts
  resources :orders

  get "/signin" => "sessions#new", as: :new_sessions
  post "/signin" => "sessions#create", as: :sessions
  delete "/signout" => "sessions#destroy", as: :destroy_session
  post "/carts/add" => "carts#add"
  post "/carts/remove" => "carts#remove"
  get "orders/placed/" => "orders#placed", as: :placed_order
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :menuitems
  validates :qty, :numericality => { greater_than: 0 }

  def self.find_item(id)
    find_by("menuitem_id = ?", id)
  end

  def self.calculate_total(id)
    where("user_id =?", id).sum(:price)
  end
end

app/models/menuitem.rb
class Menuitem < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  validates :price, presence: true
  validates :cat, presence: true

  def self.category(catg)
    where("cat = ?", catg)
  end

  def self.category_list
    distinct.pluck(:cat)
  end

  def self.increment
    self.qty += 1
  end
end

app/models/order.rb
class Order < ActiveRecord::Base
  has_many :order_items
  belongs_to :user

  def self.user_email

  end
end

class OrderItem < ActiveRecord::Base
  belongs_to :order
end

app/models/user.rb
class User < ApplicationRecord
  has_many :cart
  has_many :orders
  has_secure_password
  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :ensure_user_logged_in

  def ensure_user_logged_in
    unless current_user
      redirect_to "/"
    end
  end

  def current_user
    return @current_user if @current_user
    current_user_id = session[:current_user_id]
    if current_user_id
      @current_user = User.find(current_user_id)
    else
      nil
    end
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def index
    @cart = current_user.cart
    render "index"
  end

  def create
    item = Cart.find_item(params[:id])
    if item
      item.update_attribute(:qty, item.qty + 1)
    else
      menuitem = Menuitem.find(params[:id])
      new_cart = Cart.create!(
        user_id: session[:current_user_id],
        menuitem_id: params[:id],
        qty: 1,
        price: menuitem.price,
        name: menuitem.name,
      )
    end
    redirect_to customers_path
  end

  def add
    item = Cart.find(params[:id])
    item.update_attribute(:qty, item.qty + 1)
    redirect_to carts_path
  end

  def remove
    item = Cart.find(params[:id])
    if item.qty > 1
      item.update_attribute(:qty, item.qty - 1)
    else
      item.destroy
    end
    redirect_to carts_path
  end

  def destroy
    item = Cart.find(params[:id])
    item.destroy
    redirect_to carts_path
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def index
    render "index"
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :ensure_user_logged_in
  def index
      render "index"
  end
end

app/controllers/menu_controller.rb
class MenuController < ApplicationController
  def index
    render "index"
  end

  def create
    item = Menuitem.new(
      name: params[:name],
      cat: params[:category],
      price: params[:price].to_f,
    )
    if item.save
      redirect_to menu_index_path
    else
      flash[:error] = item.errors.full_messages.join(", ")
      redirect_to menu_index_path
    end
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    render "index"
  end

  def new
    cart = current_user.cart
    order = Order.create!(
      status: "Placed",
      user_id: session[:current_user_id],
      date: Date.today,
      total: cart.sum("qty * price"),
    )
    cart.each do |item|
      new_item = OrderItem.create!(
        order_id: order.id,
        menu_item_id: item.menuitem_id,
        name: item.name,
        qty: item.qty,
        price: item.price,
      )
      cart.destroy_all
    end
    redirect_to placed_order_path
  end

  def create
    order = Order.find(params[:id])
    order.update_attribute(:status, "Delivered")
    redirect_to orders_path
  end

  def show
    render "placed"
  end

  def placed
    render "placed"
  end
end

app/controllers/owners_controller.rb
class OwnersController < ApplicationController
  def index
    render "index"
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :ensure_user_logged_in

  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:current_user_id] = user.id
      if user.role == "owner"
        redirect_to owners_path
      else
        redirect_to customers_path
      end
    else
      flash[:error] = "Your login attempt was invalid.Please retry."
      redirect_to new_sessions_path
    end
  end

  def destroy
    session[:current_user_id] = nil
    @current_user = nil
    redirect_to "/"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :ensure_user_logged_in

  def new
    render "new"
  end

  def index
    render plain: User.order(:id).map { |user| user.to_pleasent_string }.join("\n")
  end

  def create
    user = User.new(
      name: params[:name],
      email: params[:email],
      password: params[:password],
    )
    if user.save
      session[:current_user_id] = user.id
      redirect_to customers_path
    else
      flash[:error] = user.errors.full_messages.join(", ")
      redirect_to new_user_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/carts/index.html.erb

<% if @cart.count > 0 %>
  <section class="CartContainer">
    <ul>
      <li class="MenuItem">
        <label class="CartItem-container">
          <p class="CartItemHeder">Name</p>
          <p class="CartItemHeder">Quantity</p>
          <p class="CartItemHeder">Price</p>
        </label>
      </li>
    </ul>
    <ul>
      <% @cart.order(:name).each do |item| %>
          <li class="MenuItem">
            <label class="MenuItem-container">
              <p class="MenuItem-price"><%= item.name %></p>
              <%= button_to "-", { :controller => "carts", :action => "remove", :id => item.id }, :method => :post, class: "CartButton" %>
              <p class="MenuItem-price"><%= item.qty %></p>
              <%= button_to "+", { :controller => "carts", :action => "add", :id => item.id }, :method => :post, class: "CartButton" %>
              <p class="MenuItem-price"><%= item.price * item.qty %></p>
              <%= button_to "X", { :controller => "carts", :action => "destroy", :id => item.id }, :method => :delete, class: "CartButton" %>
            </label>
          </li>
      <% end %>
    </ul>
  </section>
  <p class="Total">Total: <%= @cart.sum("qty*price") %></p>
  <br>
  <p class="PlaceLink"><%= link_to "Place Order", new_order_path %></p>
<% else %>
  <p style="font-size:24px;"> Your cart is empty! </p>
<% end %>


<p class="BackLink"><%= link_to "Go back", customers_path %></p>

app/views/customers/_menu-item.html.erb
<section class="CategoryContainer">
  <div class="CategoryTitle">
    <p class="CategoryTitle-text"><%= category %></p>
  </div>
  <ul>
    <% items.each do |item| %>
        <li class="MenuItem">
          <label class="MenuItem-container">
            <p class="MenuItem-name"><%= item.name %></p>
            <p class="MenuItem-price"><%= item.price %></p>
            <%= form_with(url: "/carts", method: "post", class: "AddItem") do |f| %>
              <%= f.hidden_field :id, value: item.id %>
              <%= submit_tag "Add To Cart", class: "AddItem-button" %>
          <% end %>
          </label>
        </li>
    <% end %>
  </ul>
</section>

app/views/customers/index.html.erb

<% Menuitem.category_list.each do |cat| %>
  <%= render partial: "menu-item", locals: {
               category: cat,
               items: Menuitem.category(cat),
             } %>
<% end %>


<p class="BackLink"><%= link_to "View Cart", carts_path %></p>

app/views/home/index.html.erb
<h1 class="Home-title"> Welcome to the Homepage</h1>

<h3 class="Home-authenticate">
  If you are a new user,<%= link_to "Sign up here", new_user_path %>
</h3>
<h3 class="Home-authenticate">
  If you are an existing user,<%= link_to "Sign in here", new_sessions_path %>
</h3>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CafeManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", media: "all", 'data-turbolinks-track': "reload" %>
    <%= javascript_pack_tag "application", 'data-turbolinks-track': "reload" %>
  </head>

  <body>
    <% if @current_user %>
      <p class="UserHeader">
       Welcome <%= @current_user.name %>!
       <%= link_to "Sign-out", destroy_session_path, method: "delete" %>
      </p>
    <% end %>
    <% if flash[:error] %>
      <p class="Flash-error">
        <%= flash[:error] %>
      </p>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/menu/_menu-item.html.erb
<section class="CategoryContainer">
  <div class="CategoryTitle">
    <p class="CategoryTitle-text"><%= category %></p>
  </div>
  <ul>
    <% items.each do |item| %>
        <li class="MenuItem">
          <label class="MenuItem-container">
            <p class="MenuItem-name"><%= item.name %></p>
            <p class="MenuItem-price"><%= item.price %></p>
          </label>
        </li>
    <% end %>
  </ul>
</section>

app/views/menu/index.html.erb


<main class="MenuMain">
    <article>
      <h1 class="MenuPage-title">Menu</h1>
      <%= form_with(url: "/menu", method: "post", class: "AddMenu") do %>
          <%= text_field_tag "name", nil, class: "MenuName", placeholder: "Menu name" %>
          <%= text_field_tag "category", nil, class: "MenuCategory", placeholder: "Menu cat" %>
          <%= text_field_tag "price", nil, class: "MenuPrice", placeholder: "5.50" %>
          <%= submit_tag "Add", class: "Add-button" %>
      <% end %>
      <% Menuitem.category_list.each do |cat| %>
      <%= render partial: "menu-item", locals: {
                   category: cat,
                   items: Menuitem.category(cat),
                 } %>
      <% end %>

      <p class="BackLink"><%= link_to "Go back", owners_path %></p>
    </article>
</main>

app/views/orders/_order-cat.html.erb
<section class="CategoryContainer">
  <div class="CategoryTitle">
    <p class="CategoryTitle-text"><%= orders.count > 0 ? "" : "No" %> <%= category %> Orders</p>
  </div>
  <ul>
    <% orders.each do |order| %>
        <li class="MenuItem">
          <label class="MenuItem-container">
            <p class="MenuItem-price"><%= order.id %></p>
        <p class="MenuItem-price"><%= User.find(order.user_id).email %></p>
        <p class="MenuItem-price"><%= order.status %></p>
        <%= form_with(url: "/orders", method: "post", class: "AddItem") do |f| %>
          <%= f.hidden_field :id, value: order.id %>
          <%= submit_tag "Mark as Delivered", class: "AddItem-button" %>
      <% end %>
          </label>
        </li>
    <% end %>
  </ul>
</section>

app/views/orders/index.html.erb

<section class="CartContainer">

  <%= render partial: "order-cat", locals: {
               category: "Pending",
               orders: Order.where("status=?", "Placed"),
             } %>

  <%= render partial: "order-cat", locals: {
               category: "Delivered",
               orders: Order.where("status=?", "Delivered"),
             } %>

</ul>
</section>



<p class="BackLink"><%= link_to "Go back", owners_path %></p>

app/views/orders/placed.html.erb
<p> Your order has been placed </p>

<p class="BackLink"><%= link_to "Back to Menu", customers_path %></p>

app/views/owners/index.html.erb

<p class="OwnerTitle"> Owner's Portal </p>

<p class="OwnerPageLink"><%= link_to "Click to manage menu items", menu_index_path %></p>
<br>
<p class="OwnerPageLink"><%= link_to "Click to manage Orders", orders_path %></p>

app/views/users/new.html.erb
<p class="NewUsers-title">Welcome new user!</p>

<section class="UsersNew">
  <%= form_with url: users_path do |form| %>
    <div class="Form-section">
      <p class="FormInput-label">First name:</p>
      <%= form.text_field :first_name, class: "Form-input" %>
    </div>
    <div class="Form-section">
      <p class="FormInput-label">Last name:</p>
      <%= form.text_field :last_name, class: "Form-input" %>
    </div>
    <div class="Form-section">
      <p class="FormInput-label">Email:</p>
      <%= form.email_field :email, class: "Form-input" %>
    </div>
    <div class="Form-section">
      <p class="FormInput-label">Password:</p>
      <%= form.password_field :password, class: "Form-input" %>
    </div>
    <div class="Form-section">
      <%= form.submit "Sign-up!", class: "Form-submit" %>
    </div>
  <% end %>
</section>